const ACTION_CONSTANTS = {
  LOGIN_SUCCESSFUL: 'LOGIN_SUCCESSFUL',
  LOGIN_FAILED: 'LOGIN_FAILED',
  LOGIN_DATA_UPDATE: 'LOGIN_DATA_UPDATE',
  RESET_APP: 'RESET_APP',
};


export default ACTION_CONSTANTS